name: ci-cd

on:
  workflow_dispatch: # Add this trigger to allow API triggering
    inputs:
      environment:
        description: "Environment to deploy to"
        default: "staging"
      tag:
        description: "Docker image tag"
        default: "latest"

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Tag: ${{ github.event.inputs.tag }}"

      - name: Update Deployment YAML
        run: |
          yq eval '.spec.template.spec.containers[0].image = "mostfullstack/rust-demo:${{ github.event.inputs.tag }}"' -i dev/management/deployment.yaml

      - name: Commit Deployment YAML
        run: |
          git add dev/management/deployment.yaml
          git commit -m "Update deployment image to mostfullstack/rust-demo:${{ github.event.inputs.tag }}"
          git push origin main




      # - name: Apply Deployment
        # run: kubectl apply -f dev/management/deployment.yaml
