name: ci-cd

on:
  workflow_dispatch: # Add this trigger to allow API triggering
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
      tag:
        description: "Docker image tag"
        required: true
        default: "latest"

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Tag: ${{ github.event.inputs.tag }}"

      - name: Update Deployment YAML
        run: |
          yq eval '.spec.template.spec.containers[0].image = "mostfullstack/rust-demo:${{ github.event.inputs.tag }}"' -i dev/management/deployment.yaml

      # - name: Apply Deployment
        # run: kubectl apply -f dev/management/deployment.yaml
