name: k8s-non-prod-config

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Add this trigger to allow API triggering
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Deployment
        run: yq eval '.spec.template.spec.containers[0].image = "mostfullstack/rust-demo:${{ github.event.inputs.tag }}"' -i dev/management/deployment.yaml